<style>
    .fineprint {
        padding: 12px;
        background-color: #ccc;
        font-size: 80%;
    }

</style>
<script>

    //if ("AT session('role')" != 'user')  location.href='/module/users/login';

</script>
<h1>Default User Blade / {{ ucfirst($_SESSION['role']) }}</h1>

<hr>

<p class="fineprint">
    Fine Print: This is a demo application. By using this application, you agree that you are not a real person and that
    you will not use this application to solicit or accept real leads. All leads generated by this application are
    fictitious and for demonstration purposes only. You agree to hold harmless the developers of this application for
    any misuse or misunderstanding regarding the nature of the leads provided herein.
</p>

<pre>

    @DATE('Y-m-d H:i:s') - This is the current date and time in the format YYYY-MM-DD HH:MM:SS

    @date('1/1/2000')

    @AUTHOR()

    @nothing() - Not a valid blade or Fred command

    iif([ 1, "THIS", "that" ]) - Inline if statement

    @php echo 1 ? "THIS" : "THAT"; @endphp - Inline if statement using PHP syntax

    @php echo('HELLO WORLD'); @endphp

    @if( 1 ? false : true )
        This will be displayed if the condition is true.
    @else

        This will be displayed if the condition is false.
    @endif

    @author()

</pre>
