<?php
namespace Modules\App;

/*

Copyright (C) 2026, Blackrush LLC, All Rights Reserved
Created by Erik Olson, Tarpon Springs, Florida
For more information, visit BlackrushDrive.com

MIT License

Copyright (c) 2025 Erik Lee Olson for Blackrush, LLC

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.


*/

# This is the module code for the essential Yore library ðŸ”¥ðŸ˜‚ðŸ¤‘ ðŸ˜ ðŸ¤”ðŸ§µðŸ‘ˆðŸ˜ðŸ’¥

use App\Controller;
use App\Modules;
use Modules\App\Traits\ApiTrait;
use Modules\App\Traits\FredTrait;
use Modules\App\Traits\YoreTrait;
use Modules\App\Traits\WebTrait;

/**
 *
 */
class Module extends Modules {

    use FredTrait;
    use YoreTrait;
    use ApiTrait;
    use WebTrait;

    /**
     *
     */
    public function __construct() {
        // Constructor is optional
        // Constructor in Parent does nothing right now, but all modules should call it anyway
        $this->dir = __DIR__;
        parent::__construct();
    }

    public function yore_module_init(/* Controller */ $controller = null, $myName = null)
    {
        parent::yore_module_init($controller, $myName); // TODO: Change the autogenerated stub
    }



    public function yore_module_post_init()
    {
        parent::yore_module_post_init();
        $role = $_SESSION['role'] ?? null;

        if (empty($role)) return; // do nothing, probably not logged in

        // Check to see if we have a client, cna or hha record in the database and create it if not

        $this->makeSureRoleRecordExists($role);

    }

    function makeSureRoleRecordExists($role) {

        switch ($role) {
            case 'patient': case 'patients': $table = 'fhhc_patients'; break;
            case 'client': $table = 'fhhc_patients'; break;
            case 'hha': $table = 'fhhc_hha'; break;
            case 'cna': $table = 'fhhc_cna'; break;
            default:
                $table = false;
        }

        if (!$table) return; // don't do anything

        $user_id = $_SESSION['user_id'] ?? null;

        if (empty($user_id)) return; // don't do anything

        $sql = "SELECT * FROM $table WHERE user_id=$user_id";

        $rows = $this->controller->database->sql($sql)->fetchAll();

        if (empty($_SESSION['profile'])) return;
        if (empty($rows)) {
            $name = $_SESSION['profile']['name'];
            $first_name = $last_name = $name;
            $phone = $_SESSION['profile']['phone'];
            $phone = $this->controller->cleanPhoneNumber($phone);
            $email = $_SESSION['profile']['email'];
            try {
                $first_name = explode(' ', $name, 2)[0];
                $last_name = explode(' ', $name, 2)[1];
            } catch (\Exception $e) {
                // do nothing
            }
            $sql = "INSERT INTO $table SET user_id=?, email=?, phone=?, first_name=?, last_name=?";
            $this->controller->database->sql($sql, [$user_id,$email,$phone,$first_name,$last_name]);

            $sql = "SELECT * FROM $table WHERE user_id=$user_id";
            $rows = $this->controller->database->sql($sql)->fetchAll();
        }

        $_SESSION[$role] = [];

        foreach ($rows as $row) {

            $_SESSION[$role . '_id'] = $row['id'];

            foreach ($row as $var => $val) {
                $_SESSION[$role][$var] = $val;
            }
        }

    }

    function cleanUrlOfFldValues($url) {
        // Parse the URL into components
        $parts = parse_url($url);

        // Parse query into associative array
        $query = [];
        if (isset($parts['query'])) {
            parse_str($parts['query'], $query);

            // Recursively remove any key where value starts with 'fld_'
            $query = $this->removeFldValues($query);
        }

        // Rebuild the query string
        $newQuery = http_build_query($query);

        // Rebuild the full URL
        $cleanUrl = $parts['scheme'] . '://' . $parts['host'];
        if (isset($parts['port'])) {
            $cleanUrl .= ':' . $parts['port'];
        }
        if (isset($parts['path'])) {
            $cleanUrl .= $parts['path'];
        }
        if (!empty($newQuery)) {
            $cleanUrl .= '?' . $newQuery;
        }
        if (isset($parts['fragment'])) {
            $cleanUrl .= '#' . $parts['fragment'];
        }

        return $cleanUrl;
    }

    function removeFldValues($input) {
        foreach ($input as $key => $value) {
            if (is_array($value)) {
                $input[$key] = $this->removeFldValues($value);
                // Optionally remove the whole array if it's now empty
                if (empty($input[$key])) {
                    unset($input[$key]);
                }
            } elseif (is_string($value) && strpos($value, 'fld_') === 0) {
                unset($input[$key]);
            }
        }
        return $input;
    }


}