<?php
namespace Modules\Mail;

# This is the module code for Mail

/*


 ▄▄▄▄    ██▓    ▄▄▄       ▄████▄   ██ ▄█▀ ██▀███   █    ██   ██████  ██░ ██
▓█████▄ ▓██▒   ▒████▄    ▒██▀ ▀█   ██▄█▒ ▓██ ▒ ██▒ ██  ▓██▒▒██    ▒ ▓██░ ██▒
▒██▒ ▄██▒██░   ▒██  ▀█▄  ▒▓█    ▄ ▓███▄░ ▓██ ░▄█ ▒▓██  ▒██░░ ▓██▄   ▒██▀▀██░
▒██░█▀  ▒██░   ░██▄▄▄▄██ ▒▓▓▄ ▄██▒▓██ █▄ ▒██▀▀█▄  ▓▓█  ░██░  ▒   ██▒░▓█ ░██
░▓█  ▀█▓░██████▒▓█   ▓██▒▒ ▓███▀ ░▒██▒ █▄░██▓ ▒██▒▒▒█████▓ ▒██████▒▒░▓█▒░██▓
░▒▓███▀▒░ ▒░▓  ░▒▒   ▓▒█░░ ░▒ ▒  ░▒ ▒▒ ▓▒░ ▒▓ ░▒▓░░▒▓▒ ▒ ▒ ▒ ▒▓▒ ▒ ░ ▒ ░░▒░▒
▒░▒   ░ ░ ░ ▒  ░ ▒   ▒▒ ░  ░  ▒   ░ ░▒ ▒░  ░▒ ░ ▒░░░▒░ ░ ░ ░ ░▒  ░ ░ ▒ ░▒░ ░
 ░    ░   ░ ░    ░   ▒   ░        ░ ░░ ░   ░░   ░  ░░░ ░ ░ ░  ░  ░   ░  ░░ ░
 ░          ░  ░     ░  ░░ ░      ░  ░      ░        ░           ░   ░  ░  ░
      ░                  ░
Copyright (C) 2024, Blackrush LLC, All Rights Reserved
Created by Erik Olson, Tarpon Springs, Florida
For more information, visit BlackrushDrive.com

MIT License

Copyright (c) 2025 Erik Lee Olson for Blackrush, LLC

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.


*/

use App\Controller;
use App\Modules;

// You'll want to hard include this if

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

class Module extends Modules {

    private $from_address;
    private $from_name;
    private $username;
    private $password;
    private $host;
    private $port;
    private $encryption;

    public function __construct() {
        // Constructor is optional

        // Constructor in Parent does nothing right now, but all modules should call it anyway
        $this->dir = __DIR__;
        parent::__construct();

    }

    public function yore_module_init(/* Controller */ $controller = null, $myName = null)
    {
        parent::yore_module_init($controller, $myName); // TODO: Change the autogenerated stub

        $this->from_address = $this->settings->from_address;
        $this->from_name = $this->settings->from_name;
        $this->username = $this->settings->username;
        $this->password = $this->settings->garfenibbin ?? $this->settings->password;
        $this->host = $this->settings->host;
        $this->port = $this->settings->port;
        $this->encryption = $this->settings->encryption;

        /* settings.json

        {
            "from_address": "info@trackmysolutions.us",
            "from_name": "Some Guy",
            "username": "postmaster@mg.accidentresourcecenter.com",
            "password": "",
            "garfenibbin": "",
            "cipher": "AES-128-CTR",
            "driver": "smtp",
            "host": "smtp.mailgun.org",
            "port": "587",
            "encryption": "tls"
        }
        
        */
        //dd($this->settings);
        //$a = $this->send("mechickaboola@gmail.com","this is a test","THIS IS A TEST");
        //dd($a);

    }

    public function send($to, $subject, $body, $addEmbeddedImage = false) {
// Create a new PHPMailer instance
        $mail = new PHPMailer(true);

        try {
            // Server settings
            $mail->isSMTP();
            $mail->Host = $this->host;
            $mail->SMTPAuth = true;
            $mail->Username = $this->username;
            $mail->Password = $this->password;
            $mail->SMTPSecure = $this->encryption;
            $mail->Port = $this->port;

            // Sender info
            $mail->setFrom($this->from_address, $this->from_name);

            // Recipient

            if (gettype($to) == 'array') {
                foreach($to as $t) {
                    $mail->addAddress($t);
                }
            } else {
                $mail->addAddress($to);
            }

            // Content
            $mail->isHTML(true); // Set email format to HTML
            $mail->Subject = $subject;
            $mail->Body = $body;

            if ($addEmbeddedImage) {
                $mail->AddEmbeddedImage($addEmbeddedImage[0],$addEmbeddedImage[1],$addEmbeddedImage[2],$addEmbeddedImage[3],$addEmbeddedImage[4]);
            }

            // Send the email
            if ($mail->send()) {
                return "Message has been sent";
            }
        } catch (Exception $e) {
            return "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
        }

    }

    public function sendmail($to, $subject, $body)
    {
        // Create the email headers
        $headers = "From: " . $this->from_name . " <" . $this->from_address . ">\r\n";
        $headers .= "Reply-To: " . $this->from_address . "\r\n";
        $headers .= "MIME-Version: 1.0\r\n";
        $headers .= "Content-Type: text/html; charset=UTF-8\r\n";

        // Set the SMTP options in PHP
        ini_set('SMTP', $this->host);
        ini_set('smtp_port', $this->port);
        ini_set('sendmail_from', $this->from_address);
        ini_set('auth_username', $this->username);
        ini_set('auth_password', $this->password);

        // Send the email using mail() function
        if (mail($to, $subject, $body, $headers)) {
            return "Message has been sent successfully.";
        } else {
            return "Message could not be sent.";
        }
    }

}