<?php
namespace Modules\Mail;

# This is the module code for Mail

/*



 */

use App\Controller;
use App\Modules;

// You'll want to hard include this if

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

class Module extends Modules {

    private $from_address;
    private $from_name;
    private $username;
    private $password;
    private $host;
    private $port;
    private $encryption;

    public function __construct() {
        // Constructor is optional


        $this->from_address = "info@yobasic.com";
        $this->from_name = "YoreMVP Basic Mail";
        $this->username = "postmaster@mg.yobasic.com";
        $this->password = "";
        $this->host = "smtp.mailgun.org";
        $this->port = "587";
        $this->encryption = "tls";

        // Constructor in Parent does nothing right now, but all modules should call it anyway
        parent::__construct();

        //  $a=$y->mail->sendmail("mechickaboola@gmail.com","this is a test","THIS IS A TEST");

    }

    public function yore_module_init(\App\Controller $controller = null, $myName = null)
    {
        parent::yore_module_init($controller, $myName); // TODO: Change the autogenerated stub
    }

    public function send($to, $subject, $body) {
// Create a new PHPMailer instance
        $mail = new PHPMailer(true);

        try {
            // Server settings
            $mail->isSMTP();
            $mail->Host = $this->host;
            $mail->SMTPAuth = true;
            $mail->Username = $this->username;
            $mail->Password = $this->password;
            $mail->SMTPSecure = $this->encryption;
            $mail->Port = $this->port;

            // Sender info
            $mail->setFrom($this->from_address, $this->from_name);

            // Recipient
            $mail->addAddress($to);

            // Content
            $mail->isHTML(true); // Set email format to HTML
            $mail->Subject = $subject;
            $mail->Body = $body;

            // Send the email
            if ($mail->send()) {
                return "Message has been sent";
            }
        } catch (Exception $e) {
            return "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
        }

    }

    public function sendmail($to, $subject, $body)
    {
        // Create the email headers
        $headers = "From: " . $this->from_name . " <" . $this->from_address . ">\r\n";
        $headers .= "Reply-To: " . $this->from_address . "\r\n";
        $headers .= "MIME-Version: 1.0\r\n";
        $headers .= "Content-Type: text/html; charset=UTF-8\r\n";

        // Set the SMTP options in PHP
        ini_set('SMTP', $this->host);
        ini_set('smtp_port', $this->port);
        ini_set('sendmail_from', $this->from_address);
        ini_set('auth_username', $this->username);
        ini_set('auth_password', $this->password);

        // Send the email using mail() function
        if (mail($to, $subject, $body, $headers)) {
            return "Message has been sent successfully.";
        } else {
            return "Message could not be sent.";
        }
    }

}