<style>
    .fineprint {
        padding: 12px;
        background-color: #ccc;
        font-size: 80%;
    }

</style>
<script>

    //if ("AT session('role')" != 'user')  location.href='/module/users/login';

</script>
<h1>DEFAULT USER PAGE / {{ ucfirst($_SESSION['role']) }}</h1>

<hr>

<p class="fineprint">
    Fine Print: This is a demo application. By using this application, you agree that you are not a real person and that
    you will not use this application to solicit or accept real leads. All leads generated by this application are
    fictitious and for demonstration purposes only. You agree to hold harmless the developers of this application for
    any misuse or misunderstanding regarding the nature of the leads provided herein.
</p>
